export const CartActionTypes = {
    TOGGLE_CART_DROPDOWN_VISIBILITY: 'TOGGLE_CART_DROPDOWN_VISIBILITY',
    ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
    DECREASE_ITEM_QUANTITY: 'DECREASE_ITEM_QUANTITY',
    REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART'
};